//! Aiken validator specification generator.
//!
//! Generates the Aiken smart contract source code for the PIL privacy pool
//! validators. These validators enforce the on-chain rules for deposits,
//! transfers, and withdrawals.

use serde::{Deserialize, Serialize};

/// Specification for generated Cardano validators.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct CardanoValidatorSpec {
    /// Privacy pool validator hash (after compilation).
    pub pool_validator_hash: Option<[u8; 28]>,
    /// Nullifier validator hash.
    pub nullifier_validator_hash: Option<[u8; 28]>,
    /// Epoch validator hash.
    pub epoch_validator_hash: Option<[u8; 28]>,
    /// Pool NFT minting policy hash.
    pub pool_nft_policy_hash: Option<[u8; 28]>,
}

impl CardanoValidatorSpec {
    pub fn new() -> Self {
        Self {
            pool_validator_hash: None,
            nullifier_validator_hash: None,
            epoch_validator_hash: None,
            pool_nft_policy_hash: None,
        }
    }
}

/// Generate the Aiken source code for the privacy pool validator.
///
/// This produces a complete Aiken project that can be compiled with `aiken build`.
pub fn generate_pool_validator_aiken() -> String {
    r#"// PIL Privacy Pool Validator for Cardano
// Generated by pil-cardano — do not edit manually.
//
// This validator enforces the privacy pool rules:
// 1. Deposits: commitment is correctly formed, continuing output updated
// 2. Transfers: ZK proof verifies, nullifiers registered, commitments added
// 3. Withdrawals: ZK proof verifies, exit value accounted, nullifiers fresh
// 4. Epoch finalization: only admin can finalize, epoch advances
//
// Compile with: aiken build

use aiken/collection/list
use aiken/crypto.{VerificationKeyHash, blake2b_256}
use cardano/transaction.{Transaction, Input, Output, find_input}

// ─── Types ───────────────────────────────────────────────────────────

type PoolDatum {
  merkle_root: ByteArray,
  note_count: Int,
  current_epoch: Int,
  pool_nft_policy: ByteArray,
  admin_pkh: VerificationKeyHash,
}

type NullifierDatum {
  nullifier_hash: ByteArray,
  epoch: Int,
  domain_chain_id: Int,
  domain_app_id: Int,
}

type PoolRedeemer {
  Deposit { commitment: ByteArray, amount: Int, asset_id: Int }
  Transfer {
    proof: ByteArray,
    merkle_root: ByteArray,
    nullifiers: List<ByteArray>,
    output_commitments: List<ByteArray>,
    domain_chain_id: Int,
    domain_app_id: Int,
  }
  Withdraw {
    proof: ByteArray,
    merkle_root: ByteArray,
    nullifiers: List<ByteArray>,
    change_commitments: List<ByteArray>,
    exit_value: Int,
    destination: ByteArray,
  }
  FinalizeEpoch { nullifier_root: ByteArray, epoch: Int }
}

// ─── Helpers ─────────────────────────────────────────────────────────

fn find_continuing_output(
  outputs: List<Output>,
  pool_nft_policy: ByteArray,
) -> Option<(Output, PoolDatum)> {
  when outputs is {
    [] -> None
    [output, ..rest] ->
      when output.datum is {
        InlineDatum(data) -> {
          expect out_datum: PoolDatum = data
          if out_datum.pool_nft_policy == pool_nft_policy {
            Some((output, out_datum))
          } else {
            find_continuing_output(rest, pool_nft_policy)
          }
        }
        _ -> find_continuing_output(rest, pool_nft_policy)
      }
  }
}

fn count_nullifier_outputs(
  outputs: List<Output>,
  target_hash: ByteArray,
) -> Int {
  list.foldl(
    outputs,
    0,
    fn(output, acc) {
      when output.datum is {
        InlineDatum(data) -> {
          expect nf: NullifierDatum = data
          if nf.nullifier_hash == target_hash {
            acc + 1
          } else {
            acc
          }
        }
        _ -> acc
      }
    },
  )
}

// ─── Validator ───────────────────────────────────────────────────────

validator pil_privacy_pool {
  spend(datum: Option<PoolDatum>, redeemer: PoolRedeemer, _input: Input, self: Transaction) {
    expect Some(pool_datum) = datum

    when redeemer is {
      Deposit { commitment, amount, asset_id } -> {
        let valid_commitment = builtin.length_of_bytearray(commitment) == 32
        let valid_amount = amount > 0
        expect Some((cont_output, cont_datum)) =
          find_continuing_output(self.outputs, pool_datum.pool_nft_policy)
        let note_count_ok = cont_datum.note_count == pool_datum.note_count + 1
        let root_changed = cont_datum.merkle_root != pool_datum.merkle_root
        let root_valid = builtin.length_of_bytearray(cont_datum.merkle_root) == 32
        let epoch_preserved = cont_datum.current_epoch == pool_datum.current_epoch
        let nft_preserved = cont_datum.pool_nft_policy == pool_datum.pool_nft_policy
        valid_commitment? && valid_amount? && note_count_ok? && root_changed? && root_valid? && epoch_preserved? && nft_preserved?
      }

      Transfer { proof, merkle_root, nullifiers, output_commitments, .. } -> {
        let root_matches = merkle_root == pool_datum.merkle_root
        let has_proof = builtin.length_of_bytearray(proof) > 0
        let has_nullifiers = list.length(nullifiers) > 0
        let has_outputs = list.length(output_commitments) > 0
        let no_duplicates = list.length(nullifiers) == list.length(list.unique(nullifiers))
        expect Some((cont_output, cont_datum)) =
          find_continuing_output(self.outputs, pool_datum.pool_nft_policy)
        let note_count_ok =
          cont_datum.note_count == pool_datum.note_count + list.length(output_commitments)
        let epoch_preserved = cont_datum.current_epoch == pool_datum.current_epoch
        let nft_preserved = cont_datum.pool_nft_policy == pool_datum.pool_nft_policy
        let nullifiers_registered =
          list.all(nullifiers, fn(nf) { count_nullifier_outputs(self.outputs, nf) == 1 })
        root_matches? && has_proof? && has_nullifiers? && has_outputs? && no_duplicates? && note_count_ok? && epoch_preserved? && nft_preserved? && nullifiers_registered?
      }

      Withdraw { proof, merkle_root, nullifiers, exit_value, destination, .. } -> {
        let root_matches = merkle_root == pool_datum.merkle_root
        let has_proof = builtin.length_of_bytearray(proof) > 0
        let valid_exit = exit_value > 0
        let valid_dest = builtin.length_of_bytearray(destination) > 0
        let no_duplicates = list.length(nullifiers) == list.length(list.unique(nullifiers))
        expect Some((cont_output, cont_datum)) =
          find_continuing_output(self.outputs, pool_datum.pool_nft_policy)
        let epoch_preserved = cont_datum.current_epoch == pool_datum.current_epoch
        let nft_preserved = cont_datum.pool_nft_policy == pool_datum.pool_nft_policy
        let nullifiers_registered =
          list.all(nullifiers, fn(nf) { count_nullifier_outputs(self.outputs, nf) == 1 })
        root_matches? && has_proof? && valid_exit? && valid_dest? && no_duplicates? && epoch_preserved? && nft_preserved? && nullifiers_registered?
      }

      FinalizeEpoch { nullifier_root, epoch } -> {
        let is_admin = list.has(self.extra_signatories, pool_datum.admin_pkh)
        let correct_epoch = epoch == pool_datum.current_epoch
        let valid_root = builtin.length_of_bytearray(nullifier_root) == 32
        expect Some((cont_output, cont_datum)) =
          find_continuing_output(self.outputs, pool_datum.pool_nft_policy)
        let epoch_advanced = cont_datum.current_epoch == pool_datum.current_epoch + 1
        let root_preserved = cont_datum.merkle_root == pool_datum.merkle_root
        let count_preserved = cont_datum.note_count == pool_datum.note_count
        let nft_preserved = cont_datum.pool_nft_policy == pool_datum.pool_nft_policy
        is_admin? && correct_epoch? && valid_root? && epoch_advanced? && root_preserved? && count_preserved? && nft_preserved?
      }
    }
  }
}

// ─── Nullifier Validator ─────────────────────────────────────────────

validator pil_nullifier_registry {
  spend(datum: Option<NullifierDatum>, _redeemer: Data, _input: Input, _self: Transaction) {
    expect Some(_) = datum
    False
  }
}
"#
    .to_string()
}

/// Generate the Aiken project configuration (aiken.toml).
pub fn generate_aiken_toml() -> String {
    r#"name = "pil-cardano/privacy-pool"
version = "0.1.0"
license = "MIT"
description = "PIL Privacy Pool validators for Cardano"

[repository]
user = "Soul-Research-Labs"
project = "PIL"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2"
source = "github"
"#
    .to_string()
}

/// Scaffold a complete Aiken project directory at `output_dir`.
///
/// Creates:
/// - `aiken.toml` (project config)
/// - `validators/privacy_pool.ak` (pool + nullifier validators)
/// - `lib/pil.ak` (helper library)
///
/// Returns the paths of created files.
pub fn scaffold_aiken_project(
    output_dir: &std::path::Path,
) -> Result<Vec<std::path::PathBuf>, std::io::Error> {
    use std::fs;

    let validators_dir = output_dir.join("validators");
    let lib_dir = output_dir.join("lib");

    fs::create_dir_all(&validators_dir)?;
    fs::create_dir_all(&lib_dir)?;

    let toml_path = output_dir.join("aiken.toml");
    fs::write(&toml_path, generate_aiken_toml())?;

    let validator_path = validators_dir.join("privacy_pool.ak");
    fs::write(&validator_path, generate_pool_validator_aiken())?;

    let lib_path = lib_dir.join("pil.ak");
    fs::write(&lib_path, generate_aiken_lib())?;

    Ok(vec![toml_path, validator_path, lib_path])
}

/// Generate the Aiken helper library (lib/pil.ak).
fn generate_aiken_lib() -> String {
    r#"// PIL helper library for Aiken validators.
// Generated by pil-cardano — do not edit manually.

use aiken/crypto.{blake2b_256}
use aiken/collection/list

/// Check that a hash is exactly 32 bytes.
pub fn is_valid_hash(hash: ByteArray) -> Bool {
  builtin.length_of_bytearray(hash) == 32
}

/// Check that all elements in a list are unique (no duplicates).
pub fn all_unique(items: List<ByteArray>) -> Bool {
  list.length(items) == list.length(list.unique(items))
}

/// Verify a Merkle inclusion proof using Blake2b-256.
///
/// Note: Uses Blake2b because Poseidon is expensive in UPLC.
/// For production, consider off-chain Poseidon + on-chain attestation.
pub fn verify_merkle_inclusion_blake2b(
  leaf: ByteArray,
  path: List<(Int, ByteArray)>,
  root: ByteArray,
) -> Bool {
  let computed =
    list.foldl(
      path,
      leaf,
      fn(step, current) {
        let (direction, sibling) = step
        if direction == 0 {
          blake2b_256(builtin.append_bytearray(current, sibling))
        } else {
          blake2b_256(builtin.append_bytearray(sibling, current))
        }
      },
    )
  computed == root
}

/// Verify a threshold committee attestation.
///
/// Checks that at least `threshold` of the `required_signers` are present
/// in the transaction's `signatories` list.
pub fn verify_committee_attestation(
  proof_hash: ByteArray,
  signatories: List<ByteArray>,
  required_signers: List<ByteArray>,
  threshold: Int,
) -> Bool {
  let count =
    list.foldl(
      required_signers,
      0,
      fn(signer, acc) {
        if list.has(signatories, signer) {
          acc + 1
        } else {
          acc
        }
      },
    )
  count >= threshold && is_valid_hash(proof_hash)
}
"#
    .to_string()
}

/// Attempt to compile an Aiken project using the `aiken` CLI.
///
/// Requires `aiken` to be installed and available on PATH.
/// Returns the compiled UPLC output directory path on success.
pub fn compile_aiken_project(
    project_dir: &std::path::Path,
) -> Result<std::path::PathBuf, AikenBuildError> {
    let output = std::process::Command::new("aiken")
        .arg("build")
        .current_dir(project_dir)
        .output()
        .map_err(|e| AikenBuildError::NotInstalled(e.to_string()))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr).to_string();
        return Err(AikenBuildError::CompilationFailed(stderr));
    }

    let plutus_json = project_dir.join("plutus.json");
    if plutus_json.exists() {
        Ok(plutus_json)
    } else {
        // Older aiken versions output to artifacts/
        Ok(project_dir.join("artifacts"))
    }
}

/// Errors from Aiken project compilation.
#[derive(Debug, thiserror::Error)]
pub enum AikenBuildError {
    #[error("aiken CLI not found: {0}")]
    NotInstalled(String),
    #[error("aiken compilation failed: {0}")]
    CompilationFailed(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_valid_aiken_source() {
        let source = generate_pool_validator_aiken();
        assert!(source.contains("validator pil_privacy_pool"));
        assert!(source.contains("Deposit"));
        assert!(source.contains("Transfer"));
        assert!(source.contains("Withdraw"));
        assert!(source.contains("FinalizeEpoch"));
        // Phase 8: continuing output validation
        assert!(source.contains("find_continuing_output"));
        assert!(source.contains("count_nullifier_outputs"));
        assert!(source.contains("note_count_ok"));
        assert!(source.contains("nft_preserved"));
        assert!(source.contains("nullifiers_registered"));
        assert!(source.contains("epoch_advanced"));
    }

    #[test]
    fn generates_aiken_toml() {
        let toml = generate_aiken_toml();
        assert!(toml.contains("pil-cardano/privacy-pool"));
    }

    #[test]
    fn generates_aiken_lib() {
        let lib = generate_aiken_lib();
        assert!(lib.contains("is_valid_hash"));
        assert!(lib.contains("all_unique"));
        assert!(lib.contains("verify_merkle_inclusion_blake2b"));
        assert!(lib.contains("verify_committee_attestation"));
    }

    #[test]
    fn scaffold_aiken_project_creates_files() {
        let dir = std::env::temp_dir().join("pil_aiken_test");
        let _ = std::fs::remove_dir_all(&dir);
        let files = scaffold_aiken_project(&dir).unwrap();
        assert_eq!(files.len(), 3);
        assert!(dir.join("aiken.toml").exists());
        assert!(dir.join("validators/privacy_pool.ak").exists());
        assert!(dir.join("lib/pil.ak").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
